In [38]:
import pandas as pd

In [39]:
df = pd.read_excel("data.xlsx")

In [40]:
df

,name,team,total_points,date,position,value,GW,minutes,points_per_game
0,Mateo Kovačić,Man City,33,2024-03-17,MID,47,28,940,3.159574
1,Joško Gvardiol,Man City,44,2024-03-17,DEF,48,28,1472,2.690217
2,Cole Palmer,Man City,1,2024-03-17,MID,50,3,10,9.000000
3,Oscar Bobb,Man City,24,2024-03-17,MID,44,28,176,12.272727
4,Julián Álvarez,Man City,130,2024-03-17,FWD,65,28,2128,5.498120
...,...,...,...,...,...,...,...,...,...
557,Giovanni Reyna,Nott'm Forest,3,2024-03-17,MID,47,29,38,7.105263
558,Rodrigo Duarte Ribeiro,Nott'm Forest,1,2024-03-17,FWD,45,29,1,90.000000
559,Enes Ünal,Bournemouth,16,2024-03-17,FWD,50,28,53,27.169811
560,Jayden Danns,Liverpool,1,2024-03-17,FWD,44,28,7,12.857143
561,Oliver Arblaster,Sheffield Utd,3,2024-03-17,MID,45,28,26,10.384615

In [41]:
df2 = pd.read_csv("https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/2023-24/players_raw.csv")

In [42]:
df2["name"] = df2["first_name"] + " " + df2["second_name"]

In [43]:
df2.columns

Index(['assists', 'bonus', 'bps', 'chance_of_playing_next_round',
       'chance_of_playing_this_round', 'clean_sheets', 'clean_sheets_per_90',
       'code', 'corners_and_indirect_freekicks_order',
       'corners_and_indirect_freekicks_text', 'cost_change_event',
       'cost_change_event_fall', 'cost_change_start', 'cost_change_start_fall',
       'creativity', 'creativity_rank', 'creativity_rank_type',
       'direct_freekicks_order', 'direct_freekicks_text', 'dreamteam_count',
       'element_type', 'ep_next', 'ep_this', 'event_points',
       'expected_assists', 'expected_assists_per_90',
       'expected_goal_involvements', 'expected_goal_involvements_per_90',
       'expected_goals', 'expected_goals_conceded',
       'expected_goals_conceded_per_90', 'expected_goals_per_90', 'first_name',
       'form', 'form_rank', 'form_rank_type', 'goals_conceded',
       'goals_conceded_per_90', 'goals_scored', 'ict_index', 'ict_index_rank',
       'ict_index_rank_type', 'id', 'in_dreamteam', 'influence',
       'influence_rank', 'influence_rank_type', 'minutes', 'news',
       'news_added', 'now_cost', 'now_cost_rank', 'now_cost_rank_type',
       'own_goals', 'penalties_missed', 'penalties_order', 'penalties_saved',
       'penalties_text', 'photo', 'points_per_game', 'points_per_game_rank',
       'points_per_game_rank_type', 'red_cards', 'saves', 'saves_per_90',
       'second_name', 'selected_by_percent', 'selected_rank',
       'selected_rank_type', 'special', 'squad_number', 'starts',
       'starts_per_90', 'status', 'team', 'team_code', 'threat', 'threat_rank',
       'threat_rank_type', 'total_points', 'transfers_in',
       'transfers_in_event', 'transfers_out', 'transfers_out_event',
       'value_form', 'value_season', 'web_name', 'yellow_cards', 'name'],
      dtype='object')

In [44]:
df2 = df2[["name", "news_added", "news", "points_per_game", "team", "form", "value_form", "value_season"]]

In [45]:
df3 = pd.read_csv("https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/2023-24/teams.csv")

In [52]:
df_new = df2.merge(df3, left_on = "team", right_on="id")

In [53]:
df_new = df_new.rename(columns={"name_x":"name", "team":"team_code","name_y":"team", "form_x":"form"})

In [54]:
df_new

,name,news_added,news,points_per_game,team_code,form,value_form,value_season,code,draw,...,team_division,unavailable,win,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,Folarin Balogun,2023-08-31T08:55:15.272751Z,Transferred to Monaco,0.0,1,0.0,0.0,0.0,3,0,...,NaN,False,0,1350,1365,1370,1370,1330,1360,1
1,Cédric Alves Soares,None,NaN,1.0,1,0.3,0.1,0.8,3,0,...,NaN,False,0,1350,1365,1370,1370,1330,1360,1
2,Mohamed Elneny,2023-12-30T22:30:09.113694Z,NaN,2.0,1,0.3,0.1,1.4,3,0,...,NaN,False,0,1350,1365,1370,1370,1330,1360,1
3,Fábio Ferreira Vieira,2023-12-07T12:00:08.489004Z,NaN,2.4,1,0.3,0.1,4.1,3,0,...,NaN,False,0,1350,1365,1370,1370,1330,1360,1
4,Gabriel dos Santos Magalhães,2024-03-18T22:00:08.938811Z,Knock - 75% chance of playing,4.0,1,3.0,0.6,19.4,3,0,...,NaN,False,0,1350,1365,1370,1370,1330,1360,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
833,Harvey Griffiths,None,NaN,0.0,20,0.0,0.0,0.0,39,0,...,NaN,False,0,1100,1100,1085,1105,1115,1100,38
834,Yerson Mosquera,2024-01-25T09:07:40.695577Z,On loan to Villarreal until the end of the season,0.0,20,0.0,0.0,0.0,39,0,...,NaN,False,0,1100,1100,1085,1105,1115,1100,38
835,Noha Lemina,None,NaN,0.0,20,0.0,0.0,0.0,39,0,...,NaN,False,0,1100,1100,1085,1105,1115,1100,38
836,Wesley Okoduwa,None,NaN,0.0,20,0.0,0.0,0.0,39,0,...,NaN,False,0,1100,1100,1085,1105,1115,1100,38
837,Leon Chiwome,None,NaN,0.0,20,0.0,0.0,0.0,39,0,...,NaN,False,0,1100,1100,1085,1105,1115,1100,38

In [59]:
df_new=df_new[["name", "team", "news", "news_added", "points_per_game", "form", "value_form", "value_season"]]

In [66]:
tot_df = df.merge(df_new, on=["name","team"])

In [67]:
tot_df[tot_df["team"]=="Liverpool"]

,name,team,total_points,date,position,value,GW,minutes,points_per_game_x,news,news_added,points_per_game_y,form,value_form,value_season
312,Ibrahima Konaté,Liverpool,51,2024-03-17,DEF,49,28,1328,3.456325,Hamstring injury - 50% chance of playing,2024-03-08T10:30:08.423474Z,2.7,2.7,0.6,10.4
313,Konstantinos Tsimikas,Liverpool,47,2024-03-17,DEF,45,28,669,6.322870,NaN,2023-12-23T22:00:09.220836Z,3.9,0.3,0.1,10.4
315,Alisson Ramses Becker,Liverpool,87,2024-03-17,GK,58,28,1890,4.142857,Hamstring injury - Unknown return date,2024-02-16T20:00:08.685039Z,4.1,0.0,0.0,15.0
328,Thiago Alcántara do Nascimento,Liverpool,1,2024-03-17,MID,47,28,5,18.000000,Muscle injury - Unknown return date,2024-02-08T17:30:08.470239Z,1.0,0.0,0.0,0.2
331,Virgil van Dijk,Liverpool,100,2024-03-17,DEF,64,28,2187,4.115226,NaN,2023-11-09T08:30:08.885661Z,3.8,5.3,0.8,15.4
337,Cody Gakpo,Liverpool,69,2024-03-17,FWD,72,28,1136,5.466549,NaN,2023-10-01T02:00:08.267715Z,2.7,3.0,0.4,9.6
340,Mohamed Salah,Liverpool,168,2024-03-17,MID,130,28,1786,8.465845,NaN,2024-02-26T00:30:09.476744Z,7.6,0.3,0.0,12.8
343,Darwin Núñez Ribeiro,Liverpool,111,2024-03-17,FWD,75,28,1488,6.713710,Hamstring injury - 75% chance of playing,2024-03-18T22:00:09.307784Z,4.3,3.3,0.4,14.8
346,Andrew Robertson,Liverpool,36,2024-03-17,DEF,64,28,1034,3.133462,NaN,2024-03-01T13:00:10.035871Z,2.4,1.7,0.3,5.6
351,Dominik Szoboszlai,Liverpool,85,2024-03-17,MID,71,28,1673,4.572624,NaN,2024-02-05T08:30:09.549556Z,3.7,1.0,0.1,12.0
354,Diogo Teixeira da Silva,Liverpool,97,2024-03-17,MID,80,28,1044,8.362069,Knee injury - Expected back 07 Apr,2024-02-20T15:30:09.089009Z,5.1,0.0,0.0,12.1
355,Alexis Mac Allister,Liverpool,74,2024-03-17,MID,58,28,1721,3.869843,NaN,2024-01-29T06:30:09.385993Z,3.2,8.3,1.4,12.8
359,Harvey Elliott,Liverpool,59,2024-03-17,MID,48,28,731,7.264022,NaN,None,2.5,5.0,1.0,12.3
360,Joel Matip,Liverpool,21,2024-03-17,DEF,48,28,779,2.426187,Knee injury - Expected back 19 May,2023-12-03T23:30:10.074436Z,2.1,0.0,0.0,4.4
363,Caoimhin Kelleher,Liverpool,27,2024-03-17,GK,38,28,540,4.500000,NaN,None,3.9,4.7,1.2,7.1
380,James McConnell,Liverpool,3,2024-03-17,MID,44,28,3,90.000000,NaN,None,1.0,0.3,0.1,0.7
385,Trent Alexander-Arnold,Liverpool,103,2024-03-17,DEF,85,28,1622,5.715166,Knee injury - Expected back 07 Apr,2024-02-10T20:00:08.173397Z,4.9,0.0,0.0,12.1
387,Bobby Clark,Liverpool,5,2024-03-17,MID,44,28,86,5.232558,NaN,None,1.0,0.7,0.2,1.1
390,Curtis Jones,Liverpool,34,2024-03-17,MID,49,28,949,3.224447,Shin injury - 50% chance of playing,2024-02-20T15:30:09.102514Z,2.0,0.0,0.0,6.9
392,Ben Doak,Liverpool,1,2024-03-17,MID,43,28,13,6.923077,Knee injury - Unknown return date,2023-12-19T14:30:11.311171Z,1.0,0.0,0.0,0.2
395,Luis Díaz,Liverpool,102,2024-03-17,MID,75,28,1742,5.269805,NaN,2023-12-23T22:00:09.137690Z,3.8,4.0,0.5,13.6
397,Joe Gomez,Liverpool,65,2024-03-17,DEF,46,28,1352,4.326923,NaN,2023-11-13T01:00:09.440163Z,2.7,3.0,0.7,14.1
399,Jarell Quansah,Liverpool,17,2024-03-17,DEF,40,28,441,3.469388,NaN,None,1.9,1.3,0.3,4.2
446,Wataru Endo,Liverpool,32,2024-03-17,MID,54,28,997,2.888666,NaN,2024-02-26T00:30:09.982261Z,1.6,1.7,0.3,5.9
487,Ryan Gravenberch,Liverpool,28,2024-03-17,MID,50,28,837,3.010753,NaN,2024-02-26T00:30:10.017384Z,1.5,0.7,0.1,5.6
517,Conor Bradley,Liverpool,43,2024-03-17,DEF,41,28,381,10.157480,NaN,2024-02-09T16:00:10.341546Z,7.2,4.0,1.0,10.5
525,Owen Beck,Liverpool,1,2024-03-17,DEF,45,28,7,12.857143,On loan to Dundee until the end of the season,2024-01-31T09:02:32.787486Z,1.0,0.0,0.0,0.2
526,Kaide Gordon,Liverpool,1,2024-03-17,MID,45,28,1,90.000000,NaN,None,1.0,0.0,0.0,0.2
546,Jayden Danns,Liverpool,1,2024-03-17,FWD,44,28,7,12.857143,NaN,None,0.5,0.3,0.1,0.2

In [61]:
tot_df = tot_df[tot_df["news"].isna()].reset_index(drop=True)

In [62]:
tot_df

,name,team,total_points,date,position,value,GW,minutes,points_per_game_x,news,news_added,points_per_game_y,form,value_form,value_season
0,Mateo Kovačić,Man City,33,2024-03-17,MID,47,28,940,3.159574,NaN,2024-02-14T01:30:10.141884Z,1.6,1.2,0.3,7.2
1,Joško Gvardiol,Man City,44,2024-03-17,DEF,48,28,1472,2.690217,NaN,2024-02-14T01:30:11.025807Z,2.4,0.0,0.0,9.2
2,Oscar Bobb,Man City,24,2024-03-17,MID,44,28,176,12.272727,NaN,None,2.7,1.0,0.2,5.5
3,Julián Álvarez,Man City,130,2024-03-17,FWD,65,28,2128,5.498120,NaN,None,4.6,3.0,0.5,20.0
4,Phil Foden,Man City,160,2024-03-17,MID,82,28,2220,6.486486,NaN,None,5.7,7.8,1.0,19.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,Giovanni Reyna,Nott'm Forest,3,2024-03-17,MID,47,29,38,7.105263,NaN,2024-03-08T16:30:10.923429Z,1.0,0.2,0.0,0.6
396,Rodrigo Duarte Ribeiro,Nott'm Forest,1,2024-03-17,FWD,45,29,1,90.000000,NaN,None,1.0,0.0,0.0,0.2
397,Enes Ünal,Bournemouth,16,2024-03-17,FWD,50,28,53,27.169811,NaN,2024-02-28T00:30:11.115193Z,2.7,3.5,0.7,3.2
398,Jayden Danns,Liverpool,1,2024-03-17,FWD,44,28,7,12.857143,NaN,None,0.5,0.3,0.1,0.2
399,Oliver Arblaster,Sheffield Utd,3,2024-03-17,MID,45,28,26,10.384615,NaN,None,1.5,1.0,0.2,0.7

In [63]:
tot_df[tot_df["points_per_game_y"] > 0].reset_index(drop=True)

,name,team,total_points,date,position,value,GW,minutes,points_per_game_x,news,news_added,points_per_game_y,form,value_form,value_season
0,Mateo Kovačić,Man City,33,2024-03-17,MID,47,28,940,3.159574,NaN,2024-02-14T01:30:10.141884Z,1.6,1.2,0.3,7.2
1,Joško Gvardiol,Man City,44,2024-03-17,DEF,48,28,1472,2.690217,NaN,2024-02-14T01:30:11.025807Z,2.4,0.0,0.0,9.2
2,Oscar Bobb,Man City,24,2024-03-17,MID,44,28,176,12.272727,NaN,None,2.7,1.0,0.2,5.5
3,Julián Álvarez,Man City,130,2024-03-17,FWD,65,28,2128,5.498120,NaN,None,4.6,3.0,0.5,20.0
4,Phil Foden,Man City,160,2024-03-17,MID,82,28,2220,6.486486,NaN,None,5.7,7.8,1.0,19.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,Giovanni Reyna,Nott'm Forest,3,2024-03-17,MID,47,29,38,7.105263,NaN,2024-03-08T16:30:10.923429Z,1.0,0.2,0.0,0.6
393,Rodrigo Duarte Ribeiro,Nott'm Forest,1,2024-03-17,FWD,45,29,1,90.000000,NaN,None,1.0,0.0,0.0,0.2
394,Enes Ünal,Bournemouth,16,2024-03-17,FWD,50,28,53,27.169811,NaN,2024-02-28T00:30:11.115193Z,2.7,3.5,0.7,3.2
395,Jayden Danns,Liverpool,1,2024-03-17,FWD,44,28,7,12.857143,NaN,None,0.5,0.3,0.1,0.2
396,Oliver Arblaster,Sheffield Utd,3,2024-03-17,MID,45,28,26,10.384615,NaN,None,1.5,1.0,0.2,0.7

In [64]:
latest_df = tot_df

In [34]:
gk = latest_df[latest_df["position"]=="GK"].sort_values("points_per_game_y", ascending=False).reset_index(drop=True).head(5)
defenders = latest_df[latest_df["position"]=="DEF"].sort_values("points_per_game_y", ascending=False).reset_index(drop=True).head(15)
midfielders = latest_df[latest_df["position"]=="MID"].sort_values("points_per_game_y", ascending=False).reset_index(drop=True).head(15)
forwards = latest_df[latest_df["position"]=="FWD"].sort_values("points_per_game_y", ascending=False).reset_index(drop=True).head(15)

total_df = pd.concat([gk, defenders, midfielders, forwards], axis = 0).sort_values("position", ascending=False).reset_index(drop=True)

In [35]:
total_df

,name,team,total_points,date,position,value,GW,minutes,points_per_game_x,news,news_added,points_per_game_y,form
0,Bryan Mbeumo,Brentford,88,2024-03-17,MID,67,29,1286,6.158631,NaN,2023-12-06T23:30:08.432649Z,5.5,0.2
1,Mohamed Salah,Liverpool,168,2024-03-17,MID,130,28,1786,8.465845,NaN,2024-02-26T00:30:09.476744Z,7.6,0.3
2,Leon Bailey,Aston Villa,115,2024-03-17,MID,57,29,1397,7.408733,NaN,2023-12-15T09:30:09.140206Z,4.3,5.0
3,Rodrigo Hernandez,Man City,109,2024-03-17,MID,56,28,2076,4.725434,NaN,2023-12-23T22:30:09.724645Z,4.4,4.2
4,Richarlison de Andrade,Spurs,108,2024-03-17,MID,69,29,1341,7.248322,NaN,2024-03-01T14:00:10.883879Z,4.7,0.3
5,Anthony Gordon,Newcastle,130,2024-03-17,MID,61,28,2156,5.426716,NaN,2024-03-11T23:30:09.022916Z,4.8,3.7
6,Douglas Luiz Soares de Paulo,Aston Villa,137,2024-03-17,MID,57,29,2328,5.296392,NaN,2023-12-09T20:00:09.137355Z,4.9,5.5
7,Pascal Groß,Brighton,132,2024-03-17,MID,66,28,2122,5.598492,NaN,2023-09-22T14:00:07.601244Z,5.1,5.3
8,Martin Ødegaard,Arsenal,128,2024-03-17,MID,85,28,2124,5.423729,NaN,2023-11-04T21:00:08.152623Z,5.1,4.7
9,James Maddison,Spurs,94,2024-03-17,MID,80,29,1398,6.051502,NaN,2023-11-06T23:30:09.609885Z,5.2,5.3
10,Jarrod Bowen,West Ham,149,2024-03-17,MID,80,29,2427,5.525340,NaN,2024-01-07T21:30:10.877600Z,5.3,7.2
11,Phil Foden,Man City,160,2024-03-17,MID,82,28,2220,6.486486,NaN,None,5.7,7.8
12,Cole Palmer,Chelsea,141,2024-03-17,MID,57,28,1654,7.672310,NaN,2023-12-24T15:30:09.398314Z,5.9,9.0
13,Bukayo Saka,Arsenal,178,2024-03-17,MID,92,28,2175,7.365517,NaN,2024-03-07T14:30:07.436179Z,6.6,6.3
14,Son Heung-min,Spurs,168,2024-03-17,MID,100,29,1987,7.609461,NaN,2023-12-30T22:30:10.238220Z,6.7,8.7
15,David Raya Martin,Arsenal,87,2024-03-17,GK,50,28,1980,3.954545,NaN,2024-03-04T01:00:08.802779Z,4.0,2.7
16,Daniel Bentley,Wolves,17,2024-03-17,GK,39,28,292,5.239726,NaN,None,4.2,0.3
17,Caoimhin Kelleher,Liverpool,27,2024-03-17,GK,38,28,540,4.500000,NaN,None,3.9,4.7
18,André Onana,Man Utd,105,2024-03-17,GK,48,28,2430,3.888889,NaN,2023-12-30T22:30:10.448027Z,3.8,5.0
19,Alphonse Areola,West Ham,104,2024-03-17,GK,43,29,2205,4.244898,NaN,2023-12-07T23:30:10.009235Z,4.0,5.0
20,Carlton Morris,Luton,115,2024-03-17,FWD,52,29,1959,5.283308,NaN,None,4.0,3.2
21,Ollie Watkins,Aston Villa,187,2024-03-17,FWD,90,29,2479,6.789028,NaN,2024-03-14T23:30:09.032984Z,6.4,6.5
22,Dominic Solanke,Bournemouth,138,2024-03-17,FWD,72,28,2405,5.164241,NaN,2024-02-28T00:30:09.999722Z,4.9,3.0
23,Alexander Isak,Newcastle,95,2024-03-17,FWD,75,28,1310,6.526718,NaN,2024-02-23T11:30:09.430520Z,4.8,5.3
24,Julián Álvarez,Man City,130,2024-03-17,FWD,65,28,2128,5.498120,NaN,None,4.6,3.0
25,Rodrigo Muniz Carvalho,Fulham,69,2024-03-17,FWD,45,29,867,7.162630,NaN,2023-11-04T15:30:08.544057Z,4.1,7.0
26,Ivan Toney,Brentford,40,2024-03-17,FWD,82,29,810,4.444444,NaN,2023-07-05T16:30:03.752728Z,4.0,1.6
27,Rasmus Højlund,Man Utd,78,2024-03-17,FWD,70,28,1463,4.798360,NaN,2024-02-23T13:30:09.113550Z,3.9,0.0
28,Chris Wood,Nott'm Forest,86,2024-03-17,FWD,48,29,953,8.121721,NaN,2024-02-02T16:27:18.071854Z,3.9,2.8
29,Timo Werner,Spurs,30,2024-03-17,FWD,63,29,418,6.459330,NaN,None,3.8,5.0
30,Nicolas Jackson,Chelsea,87,2024-03-17,FWD,68,28,1725,4.539130,NaN,2023-12-30T22:30:09.623540Z,3.6,7.0
31,Lyle Foster,Burnley,53,2024-03-17,FWD,47,29,1130,4.221239,NaN,2024-02-10T21:00:07.725808Z,3.5,0.2
32,Antoine Semenyo,Bournemouth,83,2024-03-17,FWD,45,28,1329,5.620767,NaN,2024-01-01T13:00:10.892809Z,3.5,6.0
33,Erling Haaland,Man City,154,2024-03-17,FWD,144,28,1832,7.565502,NaN,2023-12-10T18:00:10.148960Z,6.7,5.2
34,Gabriel Fernando de Jesus,Arsenal,65,2024-03-17,FWD,78,28,1117,5.237243,NaN,2024-02-05T08:30:09.036230Z,3.4,0.7
35,Manuel Akanji,Man City,71,2024-03-17,DEF,49,28,1587,4.026465,NaN,2024-01-07T21:30:10.406147Z,3.5,4.8
36,Conor Bradley,Liverpool,43,2024-03-17,DEF,41,28,381,10.157480,NaN,2024-02-09T16:00:10.341546Z,7.2,4.0
37,Benjamin White,Arsenal,119,2024-03-17,DEF,56,28,2043,5.242291,NaN,2023-11-12T02:00:08.673390Z,4.4,8.7
38,William Saliba,Arsenal,112,2024-03-17,DEF,58,28,2430,4.148148,NaN,2023-10-09T08:30:07.861646Z,4.0,3.3
39,Oleksandr Zinchenko,Arsenal,86,2024-03-17,DEF,50,28,1427,5.423966,NaN,2024-02-05T08:30:09.070071Z,3.9,0.3
40,Konstantinos Tsimikas,Liverpool,47,2024-03-17,DEF,45,28,669,6.322870,NaN,2023-12-23T22:00:09.220836Z,3.9,0.3
41,Pedro Porro,Spurs,95,2024-03-17,DEF,58,29,2157,3.963839,NaN,2024-02-16T14:00:09.902636Z,3.8,2.7
42,Cristian Romero,Spurs,87,2024-03-17,DEF,51,29,1800,4.350000,NaN,2023-12-23T20:00:09.895702Z,3.8,6.3
43,Virgil van Dijk,Liverpool,100,2024-03-17,DEF,64,28,2187,4.115226,NaN,2023-11-09T08:30:08.885661Z,3.8,5.3
44,Vitalii Mykolenko,Everton,85,2024-03-17,DEF,46,28,1977,3.869499,NaN,2024-02-22T15:30:08.434315Z,3.7,1.5
45,John Stones,Man City,51,2024-03-17,DEF,53,28,860,5.337209,NaN,2023-12-28T09:30:09.480620Z,3.6,5.8
46,Nathan Aké,Man City,82,2024-03-17,DEF,51,28,1635,4.513761,NaN,2023-11-13T01:00:09.634159Z,3.6,2.5
47,Harry Maguire,Man Utd,56,2024-03-17,DEF,42,28,1155,4.363636,NaN,2024-02-28T00:30:10.563667Z,3.5,2.0
48,Pervis Estupiñán,Brighton,54,2024-03-17,DEF,49,28,975,4.984615,NaN,2023-11-10T02:00:09.926001Z,3.4,2.3
49,Fabian Schär,Newcastle,97,2024-03-17,DEF,54,28,2353,3.710157,NaN,2024-02-17T19:00:09.641548Z,3.5,4.3